### ISSUE TITLE
Incomplete artifacts for 2.4.5 in Bintray

### ISSUE THREAD

**Issue by vijaybandari** [FasterXML/jackson-datatype-joda#56] opened 2015-01-15 06:14 UTC
https://bintray.com/bintray/jcenter/com.fasterxml.jackson.datatype:jackson-datatype-joda/2.4.5/view/files/com/fasterxml/jackson/datatype/jackson-datatype-joda/2.4.5
Doesn't have all the artifacts (jar file)

**Comment by prb** [comment] 2015-01-15 06:19
@cowtowncoder Looks like the core JAR is missing on Central as well (http://search.maven.org/#artifactdetails%7Ccom.fasterxml.jackson.datatype%7Cjackson-datatype-joda%7C2.4.5%7Cbundle), and this would presumably be the cause of it not being available via Bintray.

**Comment by cowtowncoder** [comment] 2015-01-15 19:11
Thanks, we are looking into this. Oddly enough, directory exists, so it is missing exactly one file (jar).
I haven't seen this problem before.

We are working with Sonatype on resolving this.

**Comment by cowtowncoder** [comment] 2015-01-16 05:23
Pushed 2.4.5 again to Sonatype OSS repo. No errors or failures this time either (except for once timing out on 'mvn release:perform' -- sometime is still funky with that repo) for either `close` or `release`.
We'll see whether it'll get synced properly, I hope so.

**Comment by cowtowncoder** [comment] 2015-01-16 05:46
Looks like jar made its way. Yay!

**Closed by cowtowncoder** 2015-01-16 05:46 UTC

**Comment by vijaybandari** [comment] 2015-01-16 08:08
I still don't see in nither maven nor bintray. Am I referring to wrong repos or does it takes time to refresh in maven and bintray???
https://bintray.com/bintray/jcenter/com.fasterxml.jackson.datatype:jackson-datatype-joda/2.4.5/view/files/com/fasterxml/jackson/datatype/jackson-datatype-joda/2.4.5
http://mvnrepository.com/artifact/com.fasterxml.jackson.datatype/jackson-datatype-joda

**Comment by cowtowncoder** [comment] 2015-01-16 18:30
I base my knowledge on the "official" maven location at:

http://repo1.maven.org/maven2/com/fasterxml/jackson/datatype/jackson-datatype-joda/2.4.5/

and that is now up to date (it was missing the jar). This is the repo that we will try to make sure is updated; other usage is responsibility of using web sites.

Bintray does seem to have the jar now; maybe there was some delay? Update timestamp for jar is newer than for other components.
As to mvnrepository, I suspect it has slower update cycle; or possibly they skip directories that exist, assuming immutability.
