### ISSUE TITLE
JodaSerialization test failures: testDateMidnightSer and testDateMidnightSerWithTypeInfo

### ISSUE THREAD

**Issue by clamothe** [FasterXML/jackson-datatype-joda#53] opened 2015-01-12 10:56 UTC
I observed two test failures after checking out master and running the tests locally.

Run at 5:45pm on Jan 12, 2015 in Thailand, in a local timezone of GMT+7

```
Tests run: 15, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.073 sec <<< FAILURE! - in com.fasterxml.jackson.datatype.joda.JodaSerializationTest
testDateMidnightSer(com.fasterxml.jackson.datatype.joda.JodaSerializationTest)  Time elapsed: 0.009 sec  <<< FAILURE!
junit.framework.ComparisonFailure: expected:<"2001-05-2[5]"> but was:<"2001-05-2[4]">
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at junit.framework.Assert.assertEquals(Assert.java:107)
	at junit.framework.TestCase.assertEquals(TestCase.java:269)
	at com.fasterxml.jackson.datatype.joda.JodaSerializationTest.testDateMidnightSer(JodaSerializationTest.java:41)

testDateMidnightSerWithTypeInfo(com.fasterxml.jackson.datatype.joda.JodaSerializationTest)  Time elapsed: 0.009 sec  <<< FAILURE!
junit.framework.ComparisonFailure: expected:<...Midnight","2001-05-2[5]"]> but was:<...Midnight","2001-05-2[4]"]>
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at junit.framework.Assert.assertEquals(Assert.java:107)
	at junit.framework.TestCase.assertEquals(TestCase.java:269)
	at com.fasterxml.jackson.datatype.joda.JodaSerializationTest.testDateMidnightSerWithTypeInfo(JodaSerializationTest.java:56)
```

**Comment by cowtowncoder** [comment] 2015-01-12 22:44
Duplicate of #49 I think. Contributions welcome, as always!

**Closed** 2015-01-23 18:44 UTC
